language: python
dist: trusty
sudo: false
python:
- "2.7"
- "3.6"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then true ${CYTHON_VERSION:=0.26.1}; fi
- cython_suffix=${CYTHON_VERSION:+==$CYTHON_VERSION}
install:
- git clone --depth=50 --branch=master https://github.com/agroce/afl.git agroce/afl
- make -C agroce/afl install PREFIX=~/.local
- pip install --verbose cython${cython_suffix}
- pip install pyflakes
- pip install pycodestyle
- pip install python-afl
- pip install bintrees
- pip install sympy
- pip install z3
env:
- TASK=EXAMPLES SUBTASK=JUSTCOMPILE TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=EXAMPLES SUBTASK=NOBUGS TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=EXAMPLES SUBTASK=FREE TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=EXAMPLES SUBTASK=SMALL TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=AFL TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=AVL TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
- TASK=HYPOTHESIS TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
script:
- pyflakes tstl/*.py
- pyflakes tests/*.py
- pycodestyle tstl/*.py --max-line-length 120 --statistics --ignore=E741,E226,W504,E704,W503
- pycodestyle tstl/static/boilerplate* --max-line-length 120 --statistics --ignore=E741,E226,W504,E704,W503
- pycodestyle tests/*.py --max-line-length 120 --statistics --ignore=E741,E226,W504,E704,W503
- python setup.py install
- nosetests --verbose

